#include <iostream>
#include <cstdio>
#include <cstring>
#include "Character.h"

using namespace std;

void saveCharacterToFile(const Character& character, const char* fileName) {
    FILE* user = fopen(fileName, "wb");
    if (user) {
        fwrite(&character, sizeof(Character), 1, user);
        fclose(user);
        cout << "Character saved to " << fileName << endl;
    } else {
        cout << "Error opening file: " << fileName << endl;
    }
}

int main() {
    Character characters[40] = {
        {"Luke Skywalker", "Human", "Rebel Alliance", 100, 80, 70, 90, 85, 60, 
            {{"Force Push", "Pushes enemies with the Force", 1, 10, 5}, 
             {"Lightsaber Combat", "Skilled in lightsaber battles", 1, 5, 10}, 
             {"Jedi Mind Trick", "Influences weaker minds", 1, 15, 10}}, 
            {{"Lightsaber", "Weapon", 10, "Rare", "A Jedi's weapon"},
             {"Armor", "Armor", 5, "Common", "Protective gear"},
             {"Medpack", "Healing", 20, "Uncommon", "Restores health"}},
             "Jedi2023"},

        {"Darth Vader", "Human", "Sith Empire", 100, 90, 60, 80, 95, 70,
            {{"Force Choke", "Chokes enemies with the Force", 1, 20, 10},
             {"Lightsaber Mastery", "Expert in lightsaber duels", 1, 5, 15}, 
             {"Dark Side", "Draws power from the dark side", 1, 25, 20}}, 
            {{"Lightsaber", "Weapon", 10, "Epic", "A Sith's weapon"},
             {"Armor", "Armor", 5, "Rare", "Protective gear"},
             {"Shield", "Defense", 15, "Uncommon", "Energy shield"}},
             "SithLord"},

        {"Yoda", "Yoda", "Jedi Order", 80, 60, 90, 100, 70, 50,
            {{"Force Lightning", "Unleashes lightning on enemies", 1, 25, 15},
             {"Lightsaber Combat", "Skilled in lightsaber battles", 1, 5, 10}, 
             {"Wisdom", "Gives advice and insight", 1, 0, 0}}, 
            {{"Cane", "Weapon", 5, "Common", "A walking cane"},
             {"Holocron", "Knowledge", 0, "Legendary", "Contains Jedi knowledge"},
             {"Medpack", "Healing", 20, "Uncommon", "Restores health"}},
             "MasterYoda"},

        {"Han Solo", "Human", "Rebel Alliance", 90, 75, 85, 70, 80, 55,
            {{"Blaster Expert", "Expert in blaster usage", 1, 10, 5},
             {"Piloting", "Skilled pilot of the Millennium Falcon", 1, 0, 0},
             {"Charm", "Can persuade others easily", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
             {"Ship", "Vehicle", 50, "Epic", "Millennium Falcon"},
             {"Medpack", "Healing", 20, "Common", "Restores health"}},
             "a"},

        {"Princess Leia", "Human", "Rebel Alliance", 85, 60, 75, 85, 65, 55,
            {{"Diplomacy", "Skilled negotiator", 1, 0, 0},
             {"Leadership", "Leads the Rebel Alliance", 1, 0, 0}, 
             {"Blaster Proficiency", "Expert with a blaster", 1, 10, 5}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
             {"Holocomm", "Communication", 0, "Common", "For communication"},
             {"Medpack", "Healing", 20, "Common", "Restores health"}},
             "LeiaOrgana"},

        {"Obi-Wan Kenobi", "Human", "Jedi Order", 90, 70, 80, 90, 80, 65,
            {{"Force Push", "Pushes enemies away", 1, 10, 5},
             {"Lightsaber Duel", "Master of lightsaber combat", 1, 5, 10}, 
             {"Mind Trick", "Influences the weak-minded", 1, 15, 10}}, 
            {{"Lightsaber", "Weapon", 10, "Epic", "A Jedi's weapon"},
             {"Robes", "Clothing", 0, "Common", "Traditional Jedi robes"},
             {"Medpack", "Healing", 20, "Uncommon", "Restores health"}},
             "BenKenobi"},

        {"Chewbacca", "Wookiee", "Rebel Alliance", 100, 85, 70, 60, 90, 80,
            {{"Bowcaster", "Skilled with his bowcaster", 1, 10, 5},
             {"Strength", "Powerful Wookiee strength", 1, 0, 0}, 
             {"Loyalty", "Loyal friend and ally", 1, 0, 0}}, 
            {{"Bowcaster", "Weapon", 10, "Epic", "Wookiee weapon"},
             {"Bandolier", "Accessory", 0, "Common", "Holds ammo"},
             {"Medpack", "Healing", 20, "Common", "Restores health"}},
             "Chewie2023"},

        {"Rey", "Human", "Resistance", 90, 70, 75, 80, 75, 60,
            {{"Force Abilities", "Skilled with the Force", 1, 15, 10},
             {"Lightsaber Combat", "Skilled in lightsaber duels", 1, 5, 10}, 
             {"Jedi Training", "Trained by Luke Skywalker", 1, 0, 0}}, 
            {{"Lightsaber", "Weapon", 10, "Rare", "A Jedi's weapon"},
             {"Staff", "Weapon", 5, "Common", "Her original weapon"},
             {"Medpack", "Healing", 20, "Common", "Restores health"}},
             "JediRey"},

        {"Finn", "Human", "Resistance", 85, 70, 80, 75, 70, 65,
            {{"Blaster Proficiency", "Expert with a blaster", 1, 10, 5},
             {"Combat Training", "Skilled in combat", 1, 0, 0}, 
             {"Leadership", "Emerging leader", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
             {"Armor", "Armor", 5, "Common", "Protective gear"},
             {"Medpack", "Healing", 20, "Common", "Restores health"}},
             "Finn2023"},
        {"Ahsoka Tano", "Togruta", "Rebel Alliance", 90, 75, 80, 85, 70, 65,
            {{"Dual Lightsaber Combat", "Master of dual lightsaber combat", 1, 10, 10},
            {"Force Agility", "Enhanced agility and speed", 1, 15, 10},
            {"Strategic Mind", "Expert in battle strategies", 1, 0, 0}}, 
            {{"Lightsabers", "Weapon", 10, "Epic", "Her twin lightsabers"},
            {"Clothing", "Clothing", 0, "Common", "Traditional Jedi attire"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Ahsoka2023"},

        {"Darth Maul", "Zabrak", "Sith Empire", 95, 85, 70, 90, 80, 75,
            {{"Double-bladed Lightsaber", "Expert in dual-blade combat", 1, 15, 10},
            {"Stealth", "Skilled in remaining undetected", 1, 0, 0},
            {"Acrobatics", "Highly agile and acrobatic", 1, 10, 5}}, 
            {{"Lightsaber", "Weapon", 10, "Legendary", "A Sith's double-bladed weapon"},
            {"Cloak", "Clothing", 0, "Rare", "Dark robe for stealth"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "DarthMaul2023"},

        {"Padmé Amidala", "Human", "Galactic Senate", 85, 70, 75, 80, 60, 55,
            {{"Diplomatic Skills", "Skilled negotiator", 1, 0, 0},
            {"Blaster Proficiency", "Effective in using a blaster", 1, 10, 5},
            {"Leadership", "Strong leader", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
            {"Royal Gown", "Clothing", 0, "Common", "Formal attire"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Padme2023"},

        {"Boba Fett", "Human", "Bounty Hunter", 95, 85, 75, 60, 70, 65,
            {{"Bounty Hunting", "Expert in tracking and capturing", 1, 0, 0},
            {"Jetpack", "Skilled with a jetpack", 1, 0, 0},
            {"Blaster Skills", "Proficient with various blasters", 1, 10, 5}}, 
            {{"Blaster", "Weapon", 7, "Rare", "A bounty hunter's blaster"},
            {"Armor", "Armor", 5, "Legendary", "Customized armor"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Boba2023"},

        {"Jango Fett", "Human", "Bounty Hunter", 90, 80, 70, 75, 65, 60,
            {{"Clone Engineering", "Expert in cloning technology", 1, 0, 0},
            {"Mandalorian Combat", "Skilled in Mandalorian combat", 1, 10, 5},
            {"Jetpack Skills", "Effective in using a jetpack", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Rare", "A bounty hunter's blaster"},
            {"Armor", "Armor", 5, "Epic", "Mandalorian armor"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Jango2023"},

        {"Mace Windu", "Human", "Jedi Order", 95, 85, 75, 90, 80, 70,
            {{"Vaapad", "Master of Vaapad lightsaber form", 1, 10, 10},
            {"Force Empowerment", "Increases strength with the Force", 1, 15, 10},
            {"Leadership", "Strong leader of the Jedi", 1, 0, 0}}, 
            {{"Lightsaber", "Weapon", 10, "Legendary", "Unique purple lightsaber"},
            {"Robes", "Clothing", 0, "Common", "Traditional Jedi robes"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "MaceWindu2023"},

        {"Kylo Ren", "Human", "First Order", 90, 80, 75, 85, 70, 65,
            {{"Force Rage", "Unleashes anger to increase power", 1, 20, 10},
            {"Lightsaber Combat", "Expert in lightsaber duels", 1, 10, 5},
            {"Mind Manipulation", "Can influence others' thoughts", 1, 0, 0}}, 
            {{"Crossguard Lightsaber", "Weapon", 10, "Epic", "His unique lightsaber"},
            {"Armor", "Armor", 5, "Rare", "Protective gear"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Kylo2023"},

        {"General Grievous", "Cyborg", "Separatists", 85, 90, 80, 70, 60, 55,
            {{"Four Lightsaber Combat", "Expert in wielding multiple lightsabers", 1, 20, 10},
            {"Agility", "Highly agile and fast", 1, 15, 10},
            {"Tactical Mind", "Expert in strategy", 1, 0, 0}}, 
            {{"Lightsabers", "Weapon", 10, "Legendary", "Collects Jedi lightsabers"},
            {"Cyborg Body", "Armor", 5, "Rare", "Durable body"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Grievous2023"},

        {"C-3PO", "Droid", "Rebel Alliance", 70, 30, 40, 50, 40, 20,
            {{"Translation", "Fluent in many languages", 1, 0, 0},
            {"Protocol", "Expert in etiquette", 1, 0, 0},
            {"Navigation", "Good at navigation", 1, 0, 0}}, 
            {{"Data Pad", "Tool", 0, "Common", "For communication"},
            {"Backup Battery", "Utility", 0, "Common", "Keeps him operational"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Threepio2023"},

        {"R2-D2", "Droid", "Rebel Alliance", 85, 50, 60, 80, 75, 40,
            {{"Astromech Skills", "Expert in starship repair", 1, 0, 0},
            {"Holo Projection", "Can project holograms", 1, 0, 0},
            {"Resourcefulness", "Good at finding solutions", 1, 0, 0}}, 
            {{"Tool Kit", "Tool", 0, "Common", "For repairs"},
            {"Rocket Booster", "Utility", 0, "Uncommon", "Allows flight"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Artoo2023"},

        {"Jyn Erso", "Human", "Rebel Alliance", 85, 75, 80, 70, 65, 60,
            {{"Stealth", "Expert in sneaking and infiltration", 1, 0, 0},
            {"Blaster Proficiency", "Skilled with a blaster", 1, 10, 5},
            {"Leadership", "Strong leader", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Rare", "A reliable blaster"},
            {"Data Disk", "Tool", 0, "Uncommon", "Contains vital information"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Jyn2023"},

        {"Cassian Andor", "Human", "Rebel Alliance", 85, 70, 75, 80, 60, 65,
            {{"Espionage", "Expert in covert operations", 1, 0, 0},
            {"Blaster Proficiency", "Skilled with a blaster", 1, 10, 5},
            {"Combat Training", "Skilled in hand-to-hand combat", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
            {"Armor", "Armor", 5, "Common", "Protective gear"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Cassian2023"},

        {"Finn", "Human", "Resistance", 80, 70, 75, 65, 60, 55,
            {{"Hand-to-Hand Combat", "Skilled in close combat", 1, 0, 0},
            {"Blaster Skills", "Proficient with a blaster", 1, 10, 5},
            {"Leadership", "Emerging leader", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
            {"Armor", "Armor", 5, "Common", "Basic protective gear"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Finn2023"},

        {"Rey", "Human", "Resistance", 85, 80, 75, 85, 70, 65,
            {{"Force Abilities", "Strong connection to the Force", 1, 20, 10},
            {"Lightsaber Combat", "Skilled in lightsaber duels", 1, 10, 5},
            {"Survival Skills", "Expert in survival", 1, 0, 0}}, 
            {{"Lightsaber", "Weapon", 10, "Legendary", "Her unique lightsaber"},
            {"Jacket", "Clothing", 0, "Common", "Practical clothing"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Rey2023"},

        {"Poe Dameron", "Human", "Resistance", 85, 75, 80, 70, 60, 65,
            {{"Starfighter Pilot", "Expert in piloting starfighters", 1, 0, 0},
            {"Blaster Proficiency", "Skilled with a blaster", 1, 10, 5},
            {"Leadership", "Strong leader", 1, 0, 0}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
            {"Pilot's Jacket", "Clothing", 0, "Common", "Pilot attire"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Poe2023"},

        {"BB-8", "Droid", "Resistance", 75, 40, 60, 80, 70, 20,
            {{"Navigation", "Expert in navigation", 1, 0, 0},
            {"Repair Skills", "Can assist in repairs", 1, 0, 0},
            {"Holo Projection", "Can project holograms", 1, 0, 0}}, 
            {{"Tool Kit", "Tool", 0, "Common", "For repairs"},
            {"Data Disk", "Tool", 0, "Uncommon", "Contains vital information"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "BB82023"},

        {"Lando Calrissian", "Human", "Rebel Alliance", 80, 75, 70, 75, 60, 65,
            {{"Charm", "Expert in persuasion", 1, 0, 0},
            {"Gambling", "Skilled gambler", 1, 0, 0},
            {"Blaster Proficiency", "Skilled with a blaster", 1, 10, 5}}, 
            {{"Blaster", "Weapon", 7, "Uncommon", "A reliable blaster"},
            {"Cape", "Clothing", 0, "Common", "Stylish attire"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Lando2023"},

        {"Yoda", "Yoda's Species", "Jedi Order", 100, 90, 95, 90, 85, 75,
            {{"Force Mastery", "Unmatched in the Force", 1, 30, 10},
            {"Lightsaber Combat", "Expert in lightsaber duels", 1, 20, 10},
            {"Wisdom", "Master of wisdom and teachings", 1, 0, 0}}, 
            {{"Lightsaber", "Weapon", 10, "Legendary", "His unique lightsaber"},
            {"Robes", "Clothing", 0, "Common", "Traditional Jedi robes"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Yoda2023"},

        {"Snoke", "Human", "First Order", 90, 80, 85, 75, 70, 65,
            {{"Force Manipulation", "Skilled in manipulating the Force", 1, 20, 10},
            {"Leadership", "Leader of the First Order", 1, 0, 0},
            {"Mind Control", "Can control the thoughts of others", 1, 0, 0}}, 
            {{"Cloak", "Clothing", 0, "Rare", "Dark robe for stealth"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Snoke2023"},

        {"Emperor Palpatine", "Human", "Sith Empire", 95, 90, 85, 95, 80, 75,
            {{"Sith Mastery", "Expert in Sith techniques", 1, 30, 10},
            {"Force Lightning", "Skilled in Force lightning", 1, 20, 10},
            {"Manipulation", "Expert in manipulating others", 1, 0, 0}}, 
            {{"Cloak", "Clothing", 0, "Rare", "Imperial robe"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Palpatine2023"},

        {"Aayla Secura", "Twi'lek", "Jedi Order", 85, 70, 75, 80, 60, 55,
            {{"Lightsaber Combat", "Skilled in lightsaber duels", 1, 10, 5},
            {"Agility", "Highly agile and fast", 1, 15, 10},
            {"Force Abilities", "Good connection to the Force", 1, 0, 0}}, 
            {{"Lightsaber", "Weapon", 10, "Rare", "Her unique lightsaber"},
            {"Robes", "Clothing", 0, "Common", "Traditional Jedi robes"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Aayla2023"},

        {"Asajj Ventress", "Dathomirian", "Separatists", 90, 80, 75, 70, 60, 65,
            {{"Sith Training", "Expert in dark side techniques", 1, 20, 10},
            {"Dual Lightsaber Combat", "Skilled in dual-wielding", 1, 10, 5},
            {"Stealth", "Expert in sneaking", 1, 0, 0}}, 
            {{"Lightsabers", "Weapon", 10, "Legendary", "Her dual lightsabers"},
            {"Armor", "Armor", 5, "Rare", "Protective gear"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "Ventress2023"},

        {"Mon Mothma", "Human", "Rebel Alliance", 80, 70, 75, 70, 60, 65,
            {{"Diplomacy", "Skilled in negotiation", 1, 0, 0},
            {"Leadership", "Strong leader of the Rebellion", 1, 0, 0},
            {"Tactical Mind", "Good at planning", 1, 0, 0}}, 
            {{"Communicator", "Tool", 0, "Common", "For communication"},
            {"Formal Attire", "Clothing", 0, "Common", "Formal clothing"},
            {"Medpack", "Healing", 20, "Common", "Restores health"}},
            "MonMothma2023"}

             
    };

    const char* fileNames[40] = {
    "../assets/data/characters/luke_skywalker.bin",
    "../assets/data/characters/darth_vader.bin",
    "../assets/data/characters/yoda.bin",
    "../assets/data/characters/han_solo.bin",
    "../assets/data/characters/princess_leia.bin",
    "../assets/data/characters/obi_wan_kenobi.bin",
    "../assets/data/characters/chewbacca.bin",
    "../assets/data/characters/rey.bin",
    "../assets/data/characters/finn.bin",
    "../assets/data/characters/jar_jar_binks.bin",

    "../assets/data/characters/padme_amidala.bin",
    "../assets/data/characters/c-3po.bin",
    "../assets/data/characters/r2-d2.bin",
    "../assets/data/characters/boba_fett.bin",
    "../assets/data/characters/jango_fett.bin",
    "../assets/data/characters/dooku.bin",
    "../assets/data/characters/maul.bin",
    "../assets/data/characters/ashoka_tano.bin",
    "../assets/data/characters/kylo_ren.bin",
    "../assets/data/characters/hux.bin",

    "../assets/data/characters/snap_wexley.bin",
    "../assets/data/characters/greez.bin",
    "../assets/data/characters/finiss_valorum.bin",
    "../assets/data/characters/grievous.bin",
    "../assets/data/characters/jarvis.bin",
    "../assets/data/characters/mon_mothma.bin",
    "../assets/data/characters/ackbar.bin",
    "../assets/data/characters/darth_maul.bin",
    "../assets/data/characters/nute_gunray.bin",
    "../assets/data/characters/whill.bin",

    "../assets/data/characters/wicket_warrick.bin",
    "../assets/data/characters/ackbar.bin",
    "../assets/data/characters/teebo.bin",
    "../assets/data/characters/kilowog.bin",
    "../assets/data/characters/lando_calrissian.bin",
    "../assets/data/characters/sabine_wren.bin",
    "../assets/data/characters/ezra_bridger.bin",
    "../assets/data/characters/thrawn.bin",
    "../assets/data/characters/cassian_andor.bin",
    "../assets/data/characters/jyn_erso.bin"
};


    for (int i = 0; i < 40; i++) {
        saveCharacterToFile(characters[i], fileNames[i]);
    }

    return 0;
}
